name: simple-action
on: [push]
jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@v1
        id: greet
        with:
          who-to-greet: 'Swagata'
      - name: echo JS Action Output
        run: echo "Welcome at ${{ steps.greet.outputs.time }}"

      