name: Actions Workflow
on: 
  push:
  pull_request:
    types: [opened, reopened, closed]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          pwd
          ls
      - name: checkout commit
        uses: actions/checkout@v3
      - name: list after checkout
        run : ls