name: Actions Workflow
on: 
  pull_request:
    types: [opened, reopened, closed]
  repository_dispatch:
    types: test_result
jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          pwd
          ls
          whoami
      - name: checkout commit
        uses: actions/checkout@v3
      - name: list after checkout
        run : ls